mycobot:
  hardware_interface:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
arm_controller:
  mycobot_state:
    type: joint_state_controller/JointStateController
    # publish rate may larger than (twice as large as?) spin rate of contrl
    publish_rate: 20

  # mycobot_joint1:
  #   type: position_controllers/JointPositionController
  #   joint: joint1
  #   pid:
  #     p: 30.0
  #     i: 1.0
  #     d: 0.0
  #     i_clamp: 1.0
  # mycobot_joint2:
  #   type: position_controllers/JointPositionController
  #   joint: joint2
  #   pid:
  #     p: 30.0
  #     i: 1.0
  #     d: 0.0
  #     i_clamp: 1.0
  # mycobot_joint3:
  #   type: position_controllers/JointPositionController
  #   joint: joint3
  #   pid:
  #     p: 30.0
  #     i: 1.0
  #     d: 0.0
  #     i_clamp: 1.0
  # mycobot_joint4:
  #   type: position_controllers/JointPositionController
  #   joint: joint4
  #   pid:
  #     p: 30.0
  #     i: 1.0
  #     d: 0.0
  #     i_clamp: 1.0
  # mycobot_joint5:
  #   type: position_controllers/JointPositionController
  #   joint: joint5
  #   pid:
  #     p: 30.0
  #     i: 1.0
  #     d: 0.0
  #     i_clamp: 1.0
  # mycobot_joint6:
  #   type: position_controllers/JointPositionController
  #   joint: joint6
  #   pid:
  #     p: 30.0
  #     i: 1.0
  #     d: 0.0
  #     i_clamp: 1.0

  mycobot_trajectory:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1: {p: 100.0, i: 1, d: 0, i_clamp: 1}
      joint2: {p: 100.0, i: 1, d: 0, i_clamp: 1}
      joint3: {p: 100.0, i: 1, d: 0, i_clamp: 1}
      joint4: {p: 100.0, i: 1, d: 0, i_clamp: 1}
      joint5: {p: 100.0, i: 1, d: 0, i_clamp: 1}
      joint6: {p: 100.0, i: 1, d: 0, i_clamp: 1}
    constrains:
      goal_time: 10.0
      joint1:
        goal: 0.5
      joint2:
        goal: 0.5
      joint3:
        goal: 0.5
      joint4:
        goal: 0.5
      joint5:
        goal: 0.5
      joint6:
        goal: 0.5

      